### ISSUE TITLE
Entering a player name that hasn't logged in from an older date returns an error

### ISSUE THREAD

**Issue by toxicial** [MauritsWilke/HyAPI#10]
If a player has logged on from an older date onto Hypixel, the newer api data hasn't been loaded thus returning an error

**Comment by MauritsWilke** [comment]
Do you have an example username?

**Comment by toxicial** [comment]
**i currently only know one example username**
> **hey**

**Comment by MauritsWilke** [comment]
Fixed.
Error layed in the quest and challenge count :)
