### ISSUE TITLE
toLowerCase - error

### ISSUE THREAD

**Issue by toxicial** [MauritsWilke/HyAPI#12]
# upon entering a tag-less guild
> "error": "Cannot read property 'toLowerCase' of undefined"

**username / guild to use as an example**
> **guild name:** stevecat
> **username:** bb
> **username:** he

**Comment by MauritsWilke** [comment]
The tag will now be left out if the guild has no tag, this does mean that the guild colour isn't available anymore.
I am not sure if the guild colour only is there if they have a tag which im fairly certain there would be but just an issue you might run into.

**Comment by toxicial** [comment]
thank you
