### ISSUE TITLE
Cannot convert undefined or null to object - error

### ISSUE THREAD

**Issue by toxicial** [MauritsWilke/HyAPI#14]
# when you enter a player name like **minikloon** it'll send an error

>"error": "Cannot convert undefined or null to object"

i don't have any major speculations on what this issue could be caused by but i think since he's an admin on hypixel he could have some things removed from the api which returns undefined or null which could possibly be the reason why its returning the error because it has nothing to convert to an object. ¯\_(ツ)_/¯

**Comment by MauritsWilke** [comment]
U dropped an arm! -> \\
Use \\/ this to do a shrug with two arms :)
```
¯\\_(ツ)_/¯
Becomes
¯\_(ツ)_/¯
```

**Comment by toxicial** [comment]
:OO ¯\_(ツ)_/¯

**Comment by MauritsWilke** [comment]
Same error as the "hey" username!
Fixed :octocat:
